DROP TABLE IF EXISTS People;
DROP TABLE IF EXISTS Members;
DROP TABLE IF EXISTS Trainers;
DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS MemberEvents;
DROP TABLE IF EXISTS Equipment;
DROP TABLE IF EXISTS EquipmentUsage;